[platformio]
default_envs = esp32dev

[env]
test_framework = unity

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = h2zero/NimBLE-Arduino@^2
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=24

[env:native]
platform = native
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
